spring:
  application:
    name: quartz
  datasource:
    url: jdbc:mysql://localhost:3306/testdb1?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  quartz:
    job-store-type: JDBC #\u6570\u636E\u5E93\u5B58\u50A8quartz\u4EFB\u52A1\u914D\u7F6E
    jdbc:
      initialize-schema: NEVER #\u81EA\u52A8\u521D\u59CB\u5316\u8868\u7ED3\u6784\uFF0C\u7B2C\u4E00\u6B21\u542F\u52A8\u7684\u65F6\u5019\u8FD9\u91CC\u5199always